#include <bits/stdc++.h>      // (GCC only; competitive programming)
#include <vector> <array> <deque> <list> <forward_list>
#include <set> <map> <unordered_set> <unordered_map>
#include <stack> <queue>                     // adapters
#include <algorithm> <numeric>               // algorithms, accumulate, gcd, iota
#include <functional>                        // less, greater, hash
#include <string> <string_view>
#include <tuple> <utility>                   // pair, move, swap
#include <optional> <variant> <any>          // C++17
#include <chrono> <filesystem>               // extras
